# Gitpod configuration for running Shipyard in a cloud dev environment
# Docs: https://www.gitpod.io/docs/references/gitpod-yml

tasks:
  - name: Install dependencies
    init: yarn install --ignore-engines
  - name: Start development server
    command: yarn dev

ports:
  - port: 8080
    visibility: private
    onOpen: open-preview
    autoOpen: true
  - port: 4000
    visibility: public
    onOpen: open-preview
    autoOpen: true

vscode:
  extensions:
    - octref.vetur
    - dbaeumer.vscode-eslint
    - streetsidesoftware.code-spell-checker
    - PKief.material-icon-theme
    - wix.vscode-import-cost
    - oderwat.indent-rainbow
    - eamodio.gitlens
    - ms-vscode.vscode-typescript-tslint-plugin # Improved TypeScript linting
    - esbenp.prettier-vscode # Auto-formatting
    - github.vscode-pull-request-github # GitHub PR management
    - editorconfig.editorconfig # Consistent coding styles

# Optional environment variables
env:
  NODE_ENV: development
  API_URL: "https://api.example.com"
  DEBUG: "true"

# Gitpod Prebuilds: Uncomment if needed
# prebuilds:
#   - yarn install
