FROM node:lts-alpine3.14

# Define some ENV Vars
ENV PORT=80 \
  DIRECTORY=/app \
  IS_DOCKER=true

# Create and set the working directory
WORKDIR ${DIRECTORY}

# Install PNPM
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install project dependencies
RUN pnpm install --frozen-lockfile

# Copy over all project files and folders to the working directory
COPY . .

# Build initial app for production
RUN pnpm build

# Expose given port
EXPOSE ${PORT}

# Finally, run start command to serve up the built application
CMD [ "pnpm", "build-and-start"]

# Run simple healthchecks every 5 mins, to check the Shipyard's everythings great
HEALTHCHECK --interval=5m --timeout=2s --start-period=30s CMD pnpm health-check
