#!/bin/bash

# Used to setup QEMU to build arm images on amd64 processors.
# Source: https://git.io/J0ezo

# Register qemu-*-static for all supported processors except the
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged multiarch/qemu-user-static:register --reset

# Install project dependencies
yarn install --ignore-engines --immutable --no-cache --network-timeout 300000 --network-concurrency 1
