#!/bin/sh
#
# $OpenBSD$

daemon="/usr/local/bin/shipyard"
daemon_user="git"
daemon_flags="web -c /etc/shipyard/app.ini"

shipyard_directory="/var/lib/shipyard"

rc_bg=YES

. /etc/rc.d/rc.subr

rc_start() {
	${rcexec} "cd ${shipyard_directory}; ${daemon} ${daemon_flags} ${_bg}"
}

rc_cmd $1
